"use client";

import { useEffect, useMemo, useState } from "react";
import liff from "@line/liff";

type Task = { subject: string; minutes: number; detail: string; done: boolean; color: string };
type Tab = "today" | "progress" | "prayer" | "profile";
type FocusSession = { taskIndex: number; remainingSeconds: number; endsAt: number | null; paused: boolean; ended: boolean };
type SavedPlan = { tasks?: Task[]; challengeName?: string; examDate?: string; goal?: string; hours?: number; weak?: string; templeVisits?: string[]; wishes?: string[]; focusSession?: FocusSession };
const LIFF_ID = process.env.NEXT_PUBLIC_LIFF_ID || "2011050459-8bPHPFCw";
const defaultTasks: Task[] = [
  { subject: "數學", minutes: 45, detail: "弱點複習與錯題整理", done: false, color: "amber" },
  { subject: "英文", minutes: 30, detail: "單字＋閱讀練習", done: false, color: "jade" },
  { subject: "自然", minutes: 30, detail: "觀念複習與題型演練", done: false, color: "violet" },
];

export default function Home() {
  const [tab, setTab] = useState<Tab>("today"); const [tasks, setTasks] = useState<Task[]>(defaultTasks);
  const [name, setName] = useState("30 日學習挑戰"); const [examDate, setExamDate] = useState("2026-10-31"); const [goal, setGoal] = useState("穩定完成每日學習任務"); const [hours, setHours] = useState(2); const [weak, setWeak] = useState("數學");
  const [visits, setVisits] = useState<string[]>([]); const [wishes, setWishes] = useState<string[]>([]); const [wish, setWish] = useState(""); const [idToken, setIdToken] = useState<string | null>(null); const [lineName, setLineName] = useState<string | null>(null); const [syncStatus, setSyncStatus] = useState(""); const [ready, setReady] = useState(false); const [weeklyMinutes, setWeeklyMinutes] = useState(0); const [streakDays, setStreakDays] = useState(0);
  const [focusIndex, setFocusIndex] = useState<number | null>(null); const [focusSeconds, setFocusSeconds] = useState(0); const [focusEndsAt, setFocusEndsAt] = useState<number | null>(null); const [focusPaused, setFocusPaused] = useState(false); const [focusEnded, setFocusEnded] = useState(false);
  useEffect(() => { const stored = localStorage.getItem("wenchang-mvp"); if (stored) try { const data = JSON.parse(stored) as SavedPlan; if (data.tasks?.length) setTasks(data.tasks); if (data.challengeName) setName(data.challengeName); if (data.examDate) setExamDate(data.examDate); if (data.goal) setGoal(data.goal); if (data.hours) setHours(data.hours); if (data.weak) setWeak(data.weak); if (data.templeVisits) setVisits(data.templeVisits); if (data.wishes) setWishes(data.wishes); const session = data.focusSession; if (session && session.taskIndex >= 0) { const remaining = session.paused || !session.endsAt ? session.remainingSeconds : Math.max(0, Math.ceil((session.endsAt - Date.now()) / 1000)); setFocusIndex(session.taskIndex); setFocusSeconds(remaining); setFocusPaused(session.paused); setFocusEndsAt(session.paused ? null : session.endsAt); setFocusEnded(session.ended || remaining === 0); } } catch {} setReady(true); }, []);
  useEffect(() => { if (!ready) return; const focusSession = focusIndex === null ? undefined : { taskIndex: focusIndex, remainingSeconds: focusSeconds, endsAt: focusEndsAt, paused: focusPaused, ended: focusEnded }; localStorage.setItem("wenchang-mvp", JSON.stringify({ tasks, challengeName: name, examDate, goal, hours, weak, templeVisits: visits, wishes, focusSession })); }, [tasks, name, examDate, goal, hours, weak, visits, wishes, ready, focusIndex, focusSeconds, focusEndsAt, focusPaused, focusEnded]);
  useEffect(() => { liff.init({ liffId: LIFF_ID }).then(() => { if (liff.isLoggedIn()) { const token = liff.getIDToken(); if (token) setIdToken(token); setLineName(liff.getDecodedIDToken()?.name ?? null); } }).catch(() => setSyncStatus("LINE 服務暫時無法使用")); }, []);
  useEffect(() => { if (focusIndex === null || focusPaused || focusEnded || !focusEndsAt) return; const tick = () => { const remaining = Math.max(0, Math.ceil((focusEndsAt - Date.now()) / 1000)); setFocusSeconds(remaining); if (remaining === 0) { setFocusEnded(true); setFocusEndsAt(null); } }; tick(); const timer = window.setInterval(tick, 1000); return () => window.clearInterval(timer); }, [focusIndex, focusPaused, focusEnded, focusEndsAt]);
  const sync = async (nextTasks: Task[]) => { if (!idToken) return; setSyncStatus("同步中…"); try { const response = await fetch("/api/progress", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ idToken, tasks: nextTasks, hours, weak, goal, challengeName: name, examDate }) }); setSyncStatus(response.ok ? "已同步至雲端學習紀錄" : "同步未完成，資料保留在此裝置"); } catch { setSyncStatus("同步未完成，資料保留在此裝置"); } };
  useEffect(() => { if (!idToken) return; fetch("/api/progress/load", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ idToken }) }).then(response => response.ok ? response.json() : Promise.reject()).then(data => { if (!data.exists) return; if (data.tasks?.length) setTasks(data.tasks); if (data.plan) { setExamDate(data.plan.examDate); setHours(data.plan.hours); setWeak(data.plan.weak); setGoal(data.plan.goal ?? goal); } if (Array.isArray(data.visits)) setVisits(data.visits); setSyncStatus("已從雲端還原學習紀錄"); }).catch(() => setSyncStatus("雲端紀錄暫時無法讀取")); }, [idToken]);
  useEffect(() => { if (!idToken) return; fetch("/api/stats", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ idToken }) }).then(response => response.ok ? response.json() : Promise.reject()).then(data => { setWeeklyMinutes(data.weeklyMinutes ?? 0); setStreakDays(data.streakDays ?? 0); }).catch(() => undefined); }, [idToken, tasks]);
  const daysLeft = Math.max(0, Math.ceil((new Date(`${examDate}T00:00:00`).getTime() - Date.now()) / 86400000)); const completed = tasks.filter(t => t.done).length; const progress = Math.round(completed / tasks.length * 100); const energy = Math.min(100, 42 + completed * 10 + visits.length * 3); const planks = 10 + completed + visits.length; const remaining = useMemo(() => tasks.filter(t => !t.done).reduce((sum, t) => sum + t.minutes, 0), [tasks]); const pendingIndex = tasks.findIndex(task => !task.done);
  const toggleTask = (index: number) => setTasks(current => { const next = current.map((task, i) => i === index ? { ...task, done: !task.done } : task); void sync(next); return next; });
  const startFocus = () => { if (pendingIndex < 0) return; const seconds = tasks[pendingIndex].minutes * 60; setFocusIndex(pendingIndex); setFocusSeconds(seconds); setFocusEndsAt(Date.now() + seconds * 1000); setFocusPaused(false); setFocusEnded(false); };
  const pauseFocus = () => { if (!focusEndsAt) return; setFocusSeconds(Math.max(0, Math.ceil((focusEndsAt - Date.now()) / 1000))); setFocusEndsAt(null); setFocusPaused(true); };
  const resumeFocus = () => { setFocusEndsAt(Date.now() + focusSeconds * 1000); setFocusPaused(false); };
  const closeFocus = () => { setFocusIndex(null); setFocusSeconds(0); setFocusEndsAt(null); setFocusPaused(false); setFocusEnded(false); };
  const completeFocus = () => { if (focusIndex === null) return; setTasks(current => { const next = current.map((task, index) => index === focusIndex ? { ...task, done: true } : task); void sync(next); return next; }); closeFocus(); setSyncStatus("專注完成，任務已同步更新！"); };
  const login = async () => { if (!liff.isLoggedIn()) { liff.login(); return; } const token = liff.getIDToken(); if (token) { setIdToken(token); setLineName(liff.getDecodedIDToken()?.name ?? null); void sync(tasks); } };
  const reminder = async () => { if (!idToken) { await login(); return; } setSyncStatus("正在傳送提醒…"); try { const response = await fetch("/api/reminders", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ idToken, kind: "morning" }) }); setSyncStatus(response.ok ? "已傳送 LINE OA 測試提醒" : "提醒傳送失敗，請確認已加官方帳號好友"); } catch { setSyncStatus("提醒傳送失敗，請稍後再試"); } };
  const saveWish = () => { const text = wish.trim(); if (!text) return; setWishes(current => [text, ...current].slice(0, 5)); setWish(""); };
  const focusTime = `${String(Math.floor(focusSeconds / 60)).padStart(2, "0")}:${String(focusSeconds % 60).padStart(2, "0")}`;
  const today = <><section className="hero"><p className="eyebrow">{name.toUpperCase()}</p><h1>距離目標還有<br /><em>{daysLeft} 天</em></h1><div className="countdown"><span>每天 {hours} 小時・先完成今天</span></div><div className="hero-orb orb-one" /><div className="hero-orb orb-two" /></section><section className="stats"><div className="stat"><span className="stat-icon fire">🔥</span><div><small>今日能量</small><b>{energy}<i> / 100</i></b></div></div><div className="stat"><span className="stat-icon blossom">🌸</span><div><small>祈福木牌</small><b>{planks}<i> 枚</i></b></div></div></section><section className="progress-card"><div className="section-heading"><div><p className="eyebrow">今日任務・弱科 {weak}</p><h2>一步一步完成</h2></div><span className="completion">{completed} / {tasks.length} 完成</span></div><div className="progress-track"><span style={{ width: `${progress}%` }} /></div><div className="tasks">{tasks.map((task, index) => <button className={`task ${task.done ? "done" : ""}`} onClick={() => toggleTask(index)} key={`${task.subject}-${index}`} aria-pressed={task.done}><span className={`check ${task.done ? "checked" : ""}`}>{task.done ? "✓" : ""}</span><span className={`subject-dot ${task.color}`} /><span className="task-copy"><b>{task.subject}</b><small>{task.detail}</small></span><span className="minutes">{task.minutes}<small>分</small></span></button>)}</div></section>{focusIndex !== null ? <section className="focus-panel"><small>{focusEnded ? "時間到了・確認你的專注成果" : focusPaused ? "已暫停・可隨時繼續" : `正在專注・${tasks[focusIndex].subject}`}</small><b>{focusTime}</b><p>{focusEnded ? "你完成這段專注了嗎？確認後才會標記任務完成。" : "離開或重新整理後會依實際時間繼續倒數。"}</p>{focusEnded ? <div className="focus-actions"><button onClick={completeFocus}>確認完成</button><button onClick={() => { setFocusSeconds(300); setFocusEndsAt(Date.now() + 300000); setFocusPaused(false); setFocusEnded(false); }}>再加 5 分鐘</button></div> : <div className="focus-actions"><button onClick={focusPaused ? resumeFocus : pauseFocus}>{focusPaused ? "繼續專注" : "暫停"}</button><button onClick={() => { if (window.confirm("確定要提前完成並標記任務嗎？")) completeFocus(); }}>提前完成</button></div>}</section> : pendingIndex >= 0 ? <button className="start-button" onClick={startFocus}>開始專注・{tasks[pendingIndex].subject} {tasks[pendingIndex].minutes} 分鐘</button> : <section className="focus-panel complete"><b>今日全數完成 ✦</b><p>你已累積能量與祈福木牌，明天繼續前進。</p></section>}<section className="encouragement"><span>「</span><p>{completed === tasks.length ? "今天的努力已經完成，請帶著安心休息。" : `你的目標是：${goal}`}</p><span>」</span></section>{syncStatus && <p className="reminder-status">{syncStatus}</p>}</>;
  const progressView = <section className="journey"><p className="eyebrow">動態目標進度</p><h1>{name}<br /><em>倒數 {daysLeft} 天</em></h1><div className="journey-summary"><div><b>{progress}%</b><span>今日完成度</span></div><div><b>{completed}</b><span>完成任務</span></div><div><b>{remaining}</b><span>剩餘分鐘</span></div></div><div className="milestone-card"><p>你的下一個里程碑</p><b>{completed === tasks.length ? "完成今日任務，明天繼續" : `先完成 ${tasks[pendingIndex]?.subject ?? "今日任務"}`}</b><span>小步累積，會比一次衝刺走得更遠。</span></div><div className="empty-panel"><b>需要調整計畫嗎？</b><p>考試日期、每日時間、弱科與目標都可以隨時重新設定，今天的任務會重新建立。</p><button className="start-button" onClick={() => { location.href = "/goal"; }}>調整我的學習目標</button></div></section>;
  const shareResult = async () => { const text = `⛩ 文昌同行｜${name}\n今天完成 ${completed}/${tasks.length} 項任務，累積專注 ${tasks.filter(task => task.done).reduce((sum, task) => sum + task.minutes, 0)} 分鐘。\n🔥 能量 ${energy}/100　🌸 祈福木牌 ${planks} 枚\n${goal}\n${location.origin}`; try { if (navigator.share) await navigator.share({ title: "我的文昌同行成果", text }); else { await navigator.clipboard.writeText(text); setSyncStatus("成果文字已複製，可貼到 LINE 分享"); } } catch {} };
  const retentionCard = <section className="retention-card"><div><span>本週完成</span><b>{weeklyMinutes}<small> 分鐘</small></b><p>把每一次專注，累積成看得見的進步。</p></div><div className="streak-mark"><span>🔥</span><b>{streakDays}<small> 天</small></b><p>連續學習</p></div></section>;
  const shareCard = <section className="share-card"><div className="share-card-top"><span>⛩ 文昌同行</span><small>今日學習成果</small></div><h2>{name}</h2><p>完成每一小步，都是向目標靠近。</p><div className="share-metrics"><div><b>{completed}<small> / {tasks.length}</small></b><span>完成任務</span></div><div><b>{tasks.filter(task => task.done).reduce((sum, task) => sum + task.minutes, 0)}<small> 分</small></b><span>專注時間</span></div><div><b>{streakDays}<small> 天</small></b><span>連續學習</span></div></div><button onClick={shareResult}>分享我的成果 <span>↗</span></button></section>;
  const prayerMessage = progress >= 100 ? "今日圓滿。把完成感留給自己，帶著安定迎接明天。" : progress >= 50 ? "你正在前進，不必完美，持續就是最好的祈願。" : "先從眼前的一小步開始，專注會慢慢累積成力量。";
  const prayerView = <section className="journey"><p className="eyebrow">智慧宮廟・祈福同行</p><h1>為努力祈願<br /><em>也為自己留下一句話。</em></h1><section className="blessing-card"><span>今日文昌箴言</span><b>積跬步以至千里</b><p>{prayerMessage}</p><small>依今日完成度 {progress}% 生成的鼓勵內容</small></section><section className="wish-card"><b>寫下你的祈願</b><p>它會保留在此裝置，也可發佈到匿名祈福牆。</p><div><input value={wish} onChange={event => setWish(event.target.value)} placeholder="例如：希望今天能專心完成數學" maxLength={40}/><button onClick={saveWish}>留存</button></div>{wishes.length > 0 && <ul>{wishes.map((item, index) => <li key={`${item}-${index}`}>✦ {item}</li>)}</ul>}<button className="wall-link" onClick={() => { location.href = "/prayer-wall"; }}>前往匿名祈福牆 →</button></section><div className="empty-panel"><b>🌸 祈福木牌 × {planks}</b><p>目前已解鎖 {visits.length} 個巡禮徽章。到合作宮廟掃描 QR Code，收藏文化故事與專屬徽章。</p><button className="start-button" onClick={() => { location.href = "/pilgrimage"; }}>開始文昌巡禮</button></div></section>;
  const profileView = <section className="journey"><p className="eyebrow">我的帳號與服務</p><h1>{lineName ?? "學習夥伴"}<br /><em>你的學習與祈福紀錄</em></h1><div className="account-list"><div><span>目前挑戰</span><b>{name}</b></div><div><span>目標日期</span><b>{examDate}</b></div><div><span>LINE 雲端同步</span><b>{lineName ? "已連結" : "尚未連結"}</b></div></div><button className="start-button" onClick={() => { location.href = "/goal"; }}>調整學習目標</button><button className="plan-link" onClick={() => { location.href = "/pilgrimage"; }}>智慧宮廟・文昌巡禮</button><button className="test-reminder" onClick={reminder}>{lineName ? "傳送 LINE OA 測試提醒" : "連結 LINE 並同步紀錄"}</button>{syncStatus && <small className="reminder-status">{syncStatus}</small>}</section>;
  return <main><section className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark">⛩</span><span>文昌同行</span></div><div className="account"><button className="line-login" onClick={login}>{lineName ? `LINE・${lineName}` : "LINE 登入"}</button><button className="avatar" onClick={() => setTab("profile")}>{lineName?.slice(0, 1) ?? "我"}</button></div></header>{tab === "today" ? <>{today}{retentionCard}</> : tab === "progress" ? <>{progressView}{retentionCard}{shareCard}</> : tab === "prayer" ? prayerView : profileView}<nav><button className={tab === "today" ? "active" : ""} onClick={() => setTab("today")}>⌂<span>今日</span></button><button className={tab === "progress" ? "active" : ""} onClick={() => setTab("progress")}>▥<span>進度</span></button><button className={tab === "prayer" ? "active" : ""} onClick={() => setTab("prayer")}>✿<span>祈福</span></button><button className={tab === "profile" ? "active" : ""} onClick={() => setTab("profile")}>◌<span>我的</span></button></nav></section></main>;
}
