"use client";

import { useEffect, useMemo, useState } from "react";
import liff from "@line/liff";

type Subject = "數學" | "英文" | "國文" | "自然" | "社會";
type Task = { subject: Subject; minutes: number; detail: string; done: boolean; color: string };
type Screen = "today" | "progress" | "prayer" | "profile";
const defaults: Task[] = [{ subject: "數學", minutes: 45, detail: "弱點複習・一元二次方程式", done: true, color: "amber" }, { subject: "英文", minutes: 30, detail: "單字 + 閱讀練習", done: true, color: "jade" }, { subject: "自然", minutes: 30, detail: "化學基礎・酸鹼與鹽", done: false, color: "violet" }];
const colors: Record<Subject, string> = { 數學: "amber", 英文: "jade", 國文: "rose", 自然: "violet", 社會: "blue" };
const details: Record<Subject, string> = { 數學: "題組練習", 英文: "單字 + 閱讀練習", 國文: "閱讀理解・重點整理", 自然: "觀念複習・題組練習", 社會: "重點複習・歷屆題" };

function makePlan(hours: number, weak: Subject): Task[] { const total = hours * 60; const other = (Object.keys(colors) as Subject[]).filter((item) => item !== weak); const subjects = total <= 60 ? [weak, other[0]] : [weak, other[0], other[1]]; const weakMinutes = Math.min(45, Math.max(30, Math.round(total * .42 / 15) * 15)); const rest = total - weakMinutes; return subjects.map((subject, index) => ({ subject, minutes: index === 0 ? weakMinutes : Math.max(15, Math.round((rest / (subjects.length - 1)) / 15) * 15), detail: index === 0 ? `弱點加強・${details[subject]}` : details[subject], done: false, color: colors[subject] })); }

export default function Home() {
  const [tasks, setTasks] = useState<Task[]>(defaults); const [started, setStarted] = useState(false); const [showSetup, setShowSetup] = useState(false); const [hours, setHours] = useState(2); const [weak, setWeak] = useState<Subject>("數學"); const [goal, setGoal] = useState("穩定完成每天的讀書計畫"); const [ready, setReady] = useState(false); const [screen, setScreen] = useState<Screen>("today"); const [idToken, setIdToken] = useState<string | null>(null); const [lineName, setLineName] = useState<string | null>(null); const [syncing, setSyncing] = useState(false);
  useEffect(() => { const saved = localStorage.getItem("wenchang-mvp"); if (saved) { const data = JSON.parse(saved) as { tasks?: Task[]; hours?: number; weak?: Subject; goal?: string }; if (data.tasks) setTasks(data.tasks); if (data.hours) setHours(data.hours); if (data.weak) setWeak(data.weak); if (data.goal) setGoal(data.goal); } else setShowSetup(true); setReady(true); }, []);
  useEffect(() => { if (ready) localStorage.setItem("wenchang-mvp", JSON.stringify({ tasks, hours, weak, goal })); }, [tasks, hours, weak, goal, ready]);
  useEffect(() => { const liffId = process.env.NEXT_PUBLIC_LIFF_ID; if (!liffId) return; liff.init({ liffId }).then(() => { if (liff.isLoggedIn()) { const token = liff.getIDToken(); if (token) setIdToken(token); const decoded = liff.getDecodedIDToken(); setLineName(decoded?.name ?? null); } }).catch(() => undefined); }, []);
  const completed = tasks.filter((task) => task.done).length; const energy = Math.min(100, 42 + completed * 10); const planks = 10 + completed; const progress = Math.round((completed / tasks.length) * 100); const remaining = useMemo(() => tasks.filter((task) => !task.done).reduce((sum, task) => sum + task.minutes, 0), [tasks]); const journey = Array.from({ length: 30 }, (_, i) => 30 - i);
  const sync = async (nextTasks: Task[], nextHours = hours, nextWeak = weak, nextGoal = goal) => { if (!idToken) return; setSyncing(true); try { await fetch("/api/progress", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ idToken, tasks: nextTasks, hours: nextHours, weak: nextWeak, goal: nextGoal }) }); } finally { setSyncing(false); } };
  const toggleTask = (index: number) => setTasks((current) => { const next = current.map((task, i) => i === index ? { ...task, done: !task.done } : task); void sync(next); return next; });
  const saveSetup = () => { const next = makePlan(hours, weak); setTasks(next); setShowSetup(false); setStarted(false); void sync(next); };
  const login = async () => { const liffId = process.env.NEXT_PUBLIC_LIFF_ID; if (!liffId) { setShowSetup(true); return; } if (!liff.isLoggedIn()) { liff.login(); return; } const token = liff.getIDToken(); if (token) { setIdToken(token); const decoded = liff.getDecodedIDToken(); setLineName(decoded?.name ?? null); void sync(tasks); } };
  const today = <><section className="hero"><p className="eyebrow">30 日學習挑戰</p><h1>今天的每一步，<br /><em>都算數。</em></h1><div className="countdown"><span>距離國中會考</span><strong>29</strong><span>天</span></div><div className="hero-orb orb-one" /><div className="hero-orb orb-two" /></section><section className="stats" aria-label="今日學習狀態"><div className="stat"><span className="stat-icon fire">♨</span><div><small>今日能量</small><b>{energy}<i> / 100</i></b></div></div><div className="stat"><span className="stat-icon blossom">✿</span><div><small>祈福木牌</small><b>{planks}<i> 枚</i></b></div></div></section><section className="progress-card"><div className="section-heading"><div><p className="eyebrow">DAY 29 · {weak}加強</p><h2>今日任務</h2></div><span className="completion">{completed} / {tasks.length} 完成</span></div><div className="progress-track"><span style={{ width: `${progress}%` }} /></div><div className="tasks">{tasks.map((task, index) => <button className={`task ${task.done ? "done" : ""}`} onClick={() => toggleTask(index)} key={`${task.subject}-${index}`} aria-pressed={task.done}><span className={`check ${task.done ? "checked" : ""}`}>{task.done ? "✓" : ""}</span><span className={`subject-dot ${task.color}`} /><span className="task-copy"><b>{task.subject}</b><small>{task.detail}</small></span><span className="minutes">{task.minutes}<small>分</small></span></button>)}</div><div className="reward"><span>✿</span><p>完成今天全部任務，即可再獲得 <b>1 枚祈福木牌</b></p></div></section><section className="encouragement"><span>「</span><p>{completed === tasks.length ? "今日圓滿完成。你的堅持，正在為未來開路。" : `你的目標：${goal}`}</p><span>」</span></section><button className="start-button" onClick={() => setStarted(!started)}><span>{started ? "✓" : "▶"}</span>{started ? "正在進行今日挑戰" : remaining ? `開始學習 · ${remaining} 分鐘` : "今日任務已全數完成"}</button><button className="plan-link" onClick={() => setShowSetup(true)}>調整我的 30 天計畫</button></>;
  const progressView = <section className="journey"><p className="eyebrow">你的 30 日旅程</p><h1>一步一腳印，<br /><em>走向考場。</em></h1><div className="journey-summary"><div><b>1</b><span>已完成天數</span></div><div><b>{completed}</b><span>今日已完成</span></div><div><b>7</b><span>最長連續天數</span></div></div><div className="journey-heading"><h2>挑戰地圖</h2><span>今天：Day 29</span></div><div className="day-grid">{journey.map((day) => <button key={day} className={`day-cell ${day === 29 ? "current" : day > 29 ? "past" : "future"}`} onClick={() => day === 29 && setScreen("today")}><small>DAY</small><b>{day}</b>{day > 29 && <i>✓</i>}</button>)}</div><div className="journey-tip"><span>✦</span><p>完成今天任務後，會自動解鎖下一天的學習節奏。</p></div></section>;
  const placeholder = screen === "prayer" ? <section className="journey"><p className="eyebrow">祈福木牌</p><h1>努力不會白費，<br /><em>祝福一直都在。</em></h1><div className="empty-panel"><b>✿ {planks} 枚</b><p>完成今日任務即可收藏木牌。AI 籤詩與祈福牆會在核心學習流程穩定後加入。</p></div></section> : <section className="journey"><p className="eyebrow">我的挑戰</p><h1>為自己安排，<br /><em>穩穩前進。</em></h1><div className="empty-panel"><b>每日 {hours} 小時 · {weak}加強</b><p>{goal}</p><button className="start-button" onClick={() => setShowSetup(true)}>調整學習設定</button></div></section>;
  return <main><section className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark">✦</span><span>文昌同行</span></div><div className="account"><button className="line-login" onClick={login}>{lineName ? `LINE · ${lineName}` : syncing ? "同步中" : "LINE 登入"}</button><button className="avatar" onClick={() => setShowSetup(true)} aria-label="調整挑戰設定">林</button></div></header>{screen === "today" ? today : screen === "progress" ? progressView : placeholder}<nav><button className={screen === "today" ? "active" : ""} onClick={() => setScreen("today")}>⌂<span>今日</span></button><button className={screen === "progress" ? "active" : ""} onClick={() => setScreen("progress")}>▥<span>進度</span></button><button className={screen === "prayer" ? "active" : ""} onClick={() => setScreen("prayer")}>✿<span>祈福</span></button><button className={screen === "profile" ? "active" : ""} onClick={() => setScreen("profile")}>◌<span>我的</span></button></nav>{showSetup && <div className="setup-backdrop" role="dialog" aria-modal="true" aria-label="建立學習挑戰"><section className="setup-card"><p className="eyebrow">你的第一天</p><h2>建立 30 天計畫</h2><p className="setup-note">先用固定規則安排，之後再讓 AI 幫你微調。</p><label>每天可讀多久？<select value={hours} onChange={(event) => setHours(Number(event.target.value))}><option value={1}>1 小時</option><option value={2}>2 小時</option><option value={3}>3 小時</option></select></label><label>最想加強的科目？<select value={weak} onChange={(event) => setWeak(event.target.value as Subject)}>{(Object.keys(colors) as Subject[]).map((subject) => <option key={subject}>{subject}</option>)}</select></label><label>這次挑戰的目標<input value={goal} onChange={(event) => setGoal(event.target.value)} maxLength={30} /></label><button className="start-button" onClick={saveSetup}>產生我的今日任務</button><button className="later" onClick={() => setShowSetup(false)}>稍後再說</button></section></div>}</section></main>;
}
