"use client";
import { useEffect, useState } from "react";
import liff from "@line/liff";
const LIFF_ID = process.env.NEXT_PUBLIC_LIFF_ID || "2011050459-8bPHPFCw";
export default function Pilgrimage() { const [code, setCode] = useState(""); const [visits, setVisits] = useState<string[]>([]); const [notice, setNotice] = useState(""); const [idToken, setIdToken] = useState<string | null>(null);
  useEffect(() => { try { setVisits(JSON.parse(localStorage.getItem("wenchang-mvp") ?? "{}").templeVisits ?? []); } catch {} liff.init({ liffId: LIFF_ID }).then(() => { if (liff.isLoggedIn()) setIdToken(liff.getIDToken()); }).catch(() => setNotice("LINE 巡禮同步暫時無法使用")); }, []);
  useEffect(() => { if (!idToken) return; fetch("/api/visits", { headers: { "x-line-id-token": idToken } }).then(response => response.ok ? response.json() : Promise.reject()).then(data => { if (Array.isArray(data.visits)) setVisits(data.visits); }).catch(() => setNotice("巡禮資料暫時只保存在此裝置")); }, [idToken]);
  const unlock = async () => { const normalized = code.trim().toUpperCase(); if (normalized.length < 4) { setNotice("請輸入宮廟現場提供的 4 碼以上巡禮碼。"); return; } if (visits.includes(normalized)) { setNotice("這個巡禮碼已解鎖，歡迎繼續探索其他宮廟。 "); return; } const next = [...visits, normalized]; setVisits(next); const plan = JSON.parse(localStorage.getItem("wenchang-mvp") ?? "{}"); localStorage.setItem("wenchang-mvp", JSON.stringify({ ...plan, templeVisits: next })); if (idToken) { const response = await fetch("/api/visits", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ idToken, code: normalized }) }); setNotice(response.ok ? "解鎖成功！徽章與木牌已同步到雲端。" : "解鎖成功！目前暫存於此裝置，待資料表建立後可同步。 "); } else setNotice("解鎖成功！登入 LINE 後可同步徽章與木牌。 "); setCode(""); };
  return <main className="feature-page"><div className="feature-shell"><button className="back-link" onClick={() => location.href="/"}>← 返回首頁</button><section className="feature-hero temple-hero"><span className="feature-kicker">WENCHANG PILGRIMAGE</span><h1>為努力祈願，<br /><em>也為文化走一段路。</em></h1><p>在合作宮廟掃描 QR Code，收藏文昌文化故事與你的巡禮徽章。</p><div className="temple-illustration"><span>⛩</span><i>✦</i><i>✦</i><i>✦</i></div></section><section className="ritual-progress"><span>你的巡禮進度</span><b>{visits.length}<small> / 5 站</small></b><div><i style={{ width: `${Math.min(100, visits.length * 20)}%` }}/></div></section><section className="scan-card"><div className="card-title"><span>✦</span><div><b>解鎖現場巡禮</b><small>掃描合作宮廟的 QR Code 後輸入巡禮碼</small></div></div><div className="code-row"><input value={code} onChange={e=>setCode(e.target.value)} placeholder="例如 WENCHANG01"/><button onClick={unlock}>解鎖</button></div>{notice && <p className="unlock-notice">{notice}</p>}</section><section className="culture-card"><div className="culture-symbol">文</div><div><span>今日文昌箴言</span><h2>積跬步以至千里</h2><p>每一次專注與每一步巡禮，都在替目標累積力量。</p></div></section><section className="badge-card"><div><b>已收藏徽章</b><small>{visits.length ? visits.join(" · ") : "尚未解鎖，第一枚徽章正在等你"}</small></div><span>🌸</span></section><p className="feature-note">目前以巡禮碼模擬 QR 驗證；合作宮廟導入後可直接更換為專屬 QR。</p></div></main>; }
