// Editorial exploration prompts, not additional historical claims.
export const pilgrimageChapters = [
    {
        title: "城市的第一頁",
        theme: "出發 · 看見細節",
        icon: "萬",
        prompt: "找一處讓你停下腳步的建築細節：屋簷、門窗或牌匾。",
        reflection: "如果用一個詞介紹這一站，你會選什麼？",
        mission: "完成一分鐘靜觀，記住一個細節。",
        knowledge: "從建築入口與牌匾，觀察地方如何留下信仰記憶。",
        reward: "解鎖第一塊歷史碎片",
    },
    {
        title: "街區裡的守護",
        theme: "連結 · 觀察日常",
        icon: "樂",
        prompt: "站在不阻擋通行的位置，觀察廟埕與街區如何連在一起。",
        reflection: "這裡的哪個日常畫面讓你印象最深？",
        mission: "找到廟宇與街道的一個連結點。",
        knowledge: "廟宇不只是建築，也可能是街區交流與日常生活的中心。",
        reward: "解鎖第二塊歷史碎片",
    },
    {
        title: "遠方帶來的祝福",
        theme: "旅途 · 想像相遇",
        icon: "奉",
        prompt: "讀完故事，想一想：跨越距離來到一個地方，對你有什麼意義？",
        reflection: "這一段路，你最想和誰一起走？",
        mission: "在地圖上找出這一站與上一站的方向。",
        knowledge: "移動的路線，讓不同地方的信仰與故事彼此相遇。",
        reward: "解鎖第三塊歷史碎片",
    },
    {
        title: "相聚的力量",
        theme: "相遇 · 留意人群",
        icon: "朝",
        prompt: "觀察大家如何使用這個空間，不拍攝他人特寫，也不打擾參拜。",
        reflection: "人們相聚時，哪個小動作讓你感到溫暖？",
        mission: "完成一次不打擾他人的空間觀察。",
        knowledge: "公共文化空間需要被共同尊重，也由每個人的行動共同維護。",
        reward: "解鎖第四塊歷史碎片",
    },
    {
        title: "把心願帶上路",
        theme: "心意 · 寫給重要的人",
        icon: "南",
        prompt: "為想守護的人，在心裡留下一句祝福。",
        reflection: "今天想送出的一句祝福是什麼？",
        mission: "寫下一句 20 字內的祝福。",
        knowledge: "祈願是一種整理心意的方式，也能成為前進的提醒。",
        reward: "解鎖第五塊歷史碎片",
    },
    {
        title: "尋找工藝的線索",
        theme: "細看 · 發現圖案",
        icon: "天",
        prompt: "在可以觀看的範圍內，找出一種重複出現的顏色或圖案。請勿觸摸文物。",
        reflection: "你發現了什麼？它讓你想到什麼？",
        mission: "找到一個重複的圖案或色彩，並描述它。",
        knowledge: "工藝細節常把美感、祝福與地方記憶放進日常可見的物件裡。",
        reward: "解鎖第六塊歷史碎片",
    },
    {
        title: "七段記憶，成為一段旅程",
        theme: "回望 · 收藏自己的故事",
        icon: "元",
        prompt: "回想走過的七站，選出一個你最想再次造訪的地方。",
        reflection: "這趟巡禮，你最想帶走的一個記憶是什麼？",
        mission: "回顧前六站，選出一個最想重訪的地方。",
        knowledge: "當單一故事被串連起來，就會形成屬於自己的地方記憶地圖。",
        reward: "解鎖第七塊歷史碎片，開啟終章問答",
    },
];
