"use client";
import { useEffect, useMemo, useState } from "react";
type Task = { subject: string; minutes: number; detail: string; done: boolean; color: string };
const colors = ["amber", "jade", "violet", "rose", "blue"];
function buildTasks(hours: number, weak: string): Task[] { const total = Math.max(60, hours * 60); const others = ["國文", "英文", "自然", "社會"].filter(subject => subject !== weak); const first = Math.min(60, Math.max(30, Math.round(total * .45 / 15) * 15)); const second = Math.max(15, Math.round((total - first) * .55 / 15) * 15); return [{ subject: weak, minutes: first, detail: "弱點複習與錯題整理", done: false, color: colors[0] }, { subject: others[0], minutes: second, detail: "核心觀念與題型練習", done: false, color: colors[1] }, { subject: others[1], minutes: Math.max(15, total - first - second), detail: "輕量複習與重點回顧", done: false, color: colors[2] }]; }
export default function GoalPage() { const [name, setName] = useState("學測"); const [date, setDate] = useState("2026-10-31"); const [hours, setHours] = useState(2); const [weak, setWeak] = useState("數學"); const [goal, setGoal] = useState("穩定完成每日學習任務"); const [tasks, setTasks] = useState<Task[]>(() => buildTasks(2, "數學"));
  useEffect(() => { const raw = localStorage.getItem("wenchang-mvp"); if (!raw) return; try { const data = JSON.parse(raw); setName(data.challengeName ?? name); setDate(data.examDate ?? date); setHours(data.hours ?? hours); setWeak(data.weak ?? weak); setGoal(data.goal ?? goal); if (data.tasks?.length) setTasks(data.tasks); else setTasks(buildTasks(data.hours ?? 2, data.weak ?? "數學")); } catch {} }, []);
  const days = useMemo(() => Math.max(0, Math.ceil((new Date(`${date}T00:00:00`).getTime() - Date.now()) / 86400000)), [date]); const totalMinutes = tasks.reduce((sum, task) => sum + (Number(task.minutes) || 0), 0);
  const editTask = (index:number, key:"subject"|"minutes"|"detail", value:string) => setTasks(current => current.map((task, i) => i === index ? { ...task, [key]: key === "minutes" ? Math.max(0, Number(value)) : value } : task));
  const regenerate = () => setTasks(buildTasks(hours, weak)); const addTask = () => setTasks(current => current.length >= 5 ? current : [...current, { subject:"自訂項目", minutes:15, detail:"填寫讀書內容", done:false, color:colors[current.length % colors.length] }]); const removeTask = (index:number) => setTasks(current => current.length <= 1 ? current : current.filter((_, i) => i !== index));
  const save = () => { const valid = tasks.map((task, index) => ({ ...task, subject: task.subject.trim() || "自訂項目", detail: task.detail.trim() || "自主學習", minutes: Math.min(180, Math.max(5, Number(task.minutes) || 15)), done:false, color: colors[index % colors.length] })); const old = JSON.parse(localStorage.getItem("wenchang-mvp") ?? "{}"); localStorage.setItem("wenchang-mvp", JSON.stringify({ ...old, challengeName: name.trim() || "學習挑戰", examDate: date, hours, weak, goal: goal.trim() || "穩定完成每日學習任務", tasks: valid })); location.href = "/"; };
  return <main className="feature-page"><div className="feature-shell"><button className="back-link" onClick={() => location.href="/"}>← 返回首頁</button><section className="feature-hero goal-hero"><span className="feature-kicker">CUSTOM STUDY PLAN</span><h1>你的計畫，<br /><em>可以完全照你的方式安排。</em></h1><p>先設定目標，再自由調整今天每一項任務的科目、時間與內容。</p><div className="goal-orbit">{days}<small>DAY</small></div></section><section className="form-card"><div className="card-title"><span>01</span><div><b>挑戰設定</b><small>決定你的倒數與學習重心</small></div></div><label>挑戰名稱<input value={name} onChange={e=>setName(e.target.value)} maxLength={20}/></label><label>考試／目標日期<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><div className="two-fields"><label>每天可讀時間<select value={hours} onChange={e=>setHours(Number(e.target.value))}>{[1,2,3,4].map(x=><option value={x} key={x}>{x} 小時</option>)}</select></label><label>優先加強科目<select value={weak} onChange={e=>setWeak(e.target.value)}>{["數學","英文","國文","自然","社會"].map(x=><option key={x}>{x}</option>)}</select></label></div><label>這次想達成什麼<input value={goal} onChange={e=>setGoal(e.target.value)} maxLength={40}/></label><button className="regenerate-button" onClick={regenerate}>依目前設定重新產生建議任務</button></section><section className="plan-preview custom-plan"><div className="card-title"><span>02</span><div><b>自訂今日讀書計畫</b><small>共 {totalMinutes} 分鐘・可直接修改每一項</small></div></div><div className="editable-tasks">{tasks.map((task,index)=><div className="editable-task" key={`${task.color}-${index}`}><i className={task.color}/><div><input aria-label="科目" value={task.subject} onChange={e=>editTask(index,"subject",e.target.value)}/><input aria-label="內容" value={task.detail} onChange={e=>editTask(index,"detail",e.target.value)}/></div><label><input aria-label="分鐘" type="number" min="5" max="180" value={task.minutes} onChange={e=>editTask(index,"minutes",e.target.value)}/><small>分</small></label><button aria-label="移除任務" onClick={()=>removeTask(index)}>×</button></div>)}</div><button className="add-task" onClick={addTask}>＋ 新增自訂任務</button></section><section className="custom-tip"><b>小提醒</b><p>建議每日總時間接近 {hours * 60} 分鐘；但你可以依行程自由調整，計畫不必完美才值得開始。</p></section><button className="feature-cta" onClick={save}>儲存我的自訂讀書計畫 <span>→</span></button></div></main>; }
