"use client";
import { useEffect, useMemo, useState } from "react";
type Task = { subject: string; minutes: number; detail: string; done: boolean; color: string };
const colors = ["amber", "jade", "violet"];
function buildTasks(hours: number, weak: string): Task[] { const total = Math.max(60, hours * 60); const others = ["國文", "英文", "自然", "社會"].filter(subject => subject !== weak); const weakMinutes = Math.min(60, Math.max(30, Math.round(total * .45 / 15) * 15)); const secondMinutes = Math.max(15, Math.round((total - weakMinutes) * .55 / 15) * 15); return [{ subject: weak, minutes: weakMinutes, detail: "弱點複習與錯題整理", done: false, color: colors[0] }, { subject: others[0], minutes: secondMinutes, detail: "核心觀念與題型練習", done: false, color: colors[1] }, { subject: others[1], minutes: Math.max(15, total - weakMinutes - secondMinutes), detail: "輕量複習與重點回顧", done: false, color: colors[2] }]; }
export default function GoalPage() { const [name, setName] = useState("學測"); const [date, setDate] = useState("2026-10-31"); const [hours, setHours] = useState(2); const [weak, setWeak] = useState("數學"); const [goal, setGoal] = useState("穩定完成每日學習任務");
  useEffect(() => { const raw = localStorage.getItem("wenchang-mvp"); if (!raw) return; try { const data = JSON.parse(raw); setName(data.challengeName ?? name); setDate(data.examDate ?? date); setHours(data.hours ?? hours); setWeak(data.weak ?? weak); setGoal(data.goal ?? goal); } catch {} }, []);
  const days = useMemo(() => Math.max(0, Math.ceil((new Date(`${date}T00:00:00`).getTime() - Date.now()) / 86400000)), [date]); const preview = useMemo(() => buildTasks(hours, weak), [hours, weak]);
  const save = () => { const old = JSON.parse(localStorage.getItem("wenchang-mvp") ?? "{}"); localStorage.setItem("wenchang-mvp", JSON.stringify({ ...old, challengeName: name.trim() || "學習挑戰", examDate: date, hours, weak, goal: goal.trim() || "穩定完成每日學習任務", tasks: preview })); location.href = "/"; };
  return <main className="feature-page"><div className="feature-shell"><button className="back-link" onClick={() => location.href="/"}>← 返回首頁</button><section className="feature-hero goal-hero"><span className="feature-kicker">DYNAMIC GOAL SYSTEM</span><h1>把大目標，<br /><em>拆成今天能做到的事。</em></h1><p>設定一次，系統會依你的日期、時間與弱科建立可執行的每日任務。</p><div className="goal-orbit">{days}<small>DAY</small></div></section><section className="form-card"><div className="card-title"><span>01</span><div><b>設定挑戰</b><small>讓計畫更貼近你的現況</small></div></div><label>挑戰名稱<input value={name} onChange={e=>setName(e.target.value)} maxLength={20}/></label><label>考試／目標日期<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><div className="two-fields"><label>每天可讀時間<select value={hours} onChange={e=>setHours(Number(e.target.value))}>{[1,2,3,4].map(x=><option value={x} key={x}>{x} 小時</option>)}</select></label><label>優先加強科目<select value={weak} onChange={e=>setWeak(e.target.value)}>{["數學","英文","國文","自然","社會"].map(x=><option key={x}>{x}</option>)}</select></label></div><label>這次想達成什麼<input value={goal} onChange={e=>setGoal(e.target.value)} maxLength={40}/></label></section><section className="plan-preview"><div className="card-title"><span>02</span><div><b>今天的計畫預覽</b><small>共 {hours * 60} 分鐘・優先補強 {weak}</small></div></div><div className="preview-tasks">{preview.map(task=><div key={task.subject}><i className={task.color}/><span>{task.subject}<small>{task.detail}</small></span><b>{task.minutes}<small>分</small></b></div>)}</div></section><button className="feature-cta" onClick={save}>儲存設定，建立今日計畫 <span>→</span></button><p className="feature-note">你的原有紀錄會保留；今日任務會依新設定重新安排。</p></div></main>; }
