"use client";
import { useEffect, useMemo, useState } from "react";
type Task = { subject: string; minutes: number; detail: string; done: boolean; color: string };
const colors = ["amber", "jade", "violet"];
function buildTasks(hours: number, weak: string): Task[] { const total = Math.max(60, hours * 60); const others = ["國文", "英文", "自然", "社會"].filter(subject => subject !== weak); const weakMinutes = Math.min(60, Math.max(30, Math.round(total * .45 / 15) * 15)); const rest = total - weakMinutes; return [{ subject: weak, minutes: weakMinutes, detail: "弱點複習與錯題整理", done: false, color: colors[0] }, { subject: others[0], minutes: Math.max(15, Math.round(rest * .55 / 15) * 15), detail: "核心觀念與題型練習", done: false, color: colors[1] }, { subject: others[1], minutes: Math.max(15, rest - Math.max(15, Math.round(rest * .55 / 15) * 15)), detail: "輕量複習與重點回顧", done: false, color: colors[2] }]; }
export default function GoalPage() { const [name, setName] = useState("學測"); const [date, setDate] = useState("2026-10-31"); const [hours, setHours] = useState(2); const [weak, setWeak] = useState("數學"); const [goal, setGoal] = useState("穩定完成每日學習任務");
  useEffect(() => { const raw = localStorage.getItem("wenchang-mvp"); if (!raw) return; try { const data = JSON.parse(raw); setName(data.challengeName ?? name); setDate(data.examDate ?? date); setHours(data.hours ?? hours); setWeak(data.weak ?? weak); setGoal(data.goal ?? goal); } catch {} }, []);
  const days = useMemo(() => Math.max(0, Math.ceil((new Date(`${date}T00:00:00`).getTime() - Date.now()) / 86400000)), [date]); const save = () => { const old = JSON.parse(localStorage.getItem("wenchang-mvp") ?? "{}"); localStorage.setItem("wenchang-mvp", JSON.stringify({ ...old, challengeName: name.trim() || "學習挑戰", examDate: date, hours, weak, goal: goal.trim() || "穩定完成每日學習任務", tasks: buildTasks(hours, weak) })); location.href = "/"; };
  const input = { width:"100%", boxSizing:"border-box" as const, marginTop:7, padding:12, borderRadius:10, border:"1px solid #ddd6c6", background:"#fff" };
  return <main style={{ minHeight:"100vh", padding:"28px 20px", background:"#f8f4ea", color:"#20352b", fontFamily:"Arial,'Noto Sans TC',sans-serif" }}><div style={{ width:"min(100%,430px)", margin:"auto" }}><button onClick={() => location.href="/"} style={{ border:0, background:"transparent", color:"#716b5e", padding:0 }}>← 返回首頁</button><p style={{ color:"#a37d39", letterSpacing:2, fontSize:12, marginTop:24 }}>動態目標系統</p><h1>設定你的目標<br />建立可執行計畫</h1><section style={{ padding:20, borderRadius:18, background:"#fffdf8", border:"1px solid #e7dfcf" }}><label>挑戰名稱<input value={name} onChange={e=>setName(e.target.value)} maxLength={20} style={input}/></label><label style={{ display:"block", marginTop:14 }}>考試／目標日期<input type="date" value={date} onChange={e=>setDate(e.target.value)} style={input}/></label><label style={{ display:"block", marginTop:14 }}>每天可讀時間<select value={hours} onChange={e=>setHours(Number(e.target.value))} style={input}><option value={1}>1 小時</option><option value={2}>2 小時</option><option value={3}>3 小時</option><option value={4}>4 小時</option></select></label><label style={{ display:"block", marginTop:14 }}>最需要加強的科目<select value={weak} onChange={e=>setWeak(e.target.value)} style={input}>{["數學","英文","國文","自然","社會"].map(x=><option key={x}>{x}</option>)}</select></label><label style={{ display:"block", marginTop:14 }}>這次想達成什麼<input value={goal} onChange={e=>setGoal(e.target.value)} maxLength={40} style={input}/></label></section><section style={{ marginTop:16, padding:20, borderRadius:18, background:"#173e32", color:"white" }}><small>計畫預覽</small><h2 style={{ margin:"8px 0" }}>{name || "學習挑戰"}・倒數 {days} 天</h2><p style={{ lineHeight:1.7, opacity:.9 }}>每天 {hours} 小時，優先安排 {weak}；儲存後會立即生成今天的三項學習任務。</p></section><button onClick={save} style={{ width:"100%", marginTop:16, padding:14, border:0, borderRadius:12, background:"#c69543", color:"white", fontWeight:700 }}>儲存設定並建立今日計畫</button></div></main>; }
