"use client";

import { useEffect, useRef, useState } from "react";
import liff from "@line/liff";

const LIFF_ID = process.env.NEXT_PUBLIC_LIFF_ID || "2011050459-8bPHPFCw";
const temples = [
	{ code: "WENCHANG01", name: "文昌啟明堂", district: "臺北・書院街", badge: "啟", story: "昔日學子赴試前，會在書院旁靜心抄寫經句。這座小堂保留了以一筆一畫安定心緒的傳統。", insight: "先把今天最重要的一件事寫下來，專心完成它。", color: "gold" },
	{ code: "WENCHANG02", name: "魁星文運祠", district: "新北・文運巷", badge: "魁", story: "魁星象徵文章與智慧。廟內的魁斗燈提醒學子：讀書不只求快，更要找回自己的節奏。", insight: "遇到難題時，先拆成三個小步驟，再逐一處理。", color: "vermilion" },
	{ code: "WENCHANG03", name: "紫陽敬字亭", district: "桃園・古書里", badge: "敬", story: "敬字亭曾用來安放寫過的紙張，象徵珍惜知識與文字。走進這裡，也是在練習尊重每一次學習。", insight: "整理一頁筆記，讓吸收過的知識重新變得清楚。", color: "jade" },
	{ code: "WENCHANG04", name: "金榜書香殿", district: "臺中・學士路", badge: "榜", story: "殿前的書香牌記錄著來自不同學校的祈願。它提醒我們：每個人都有自己的目標與走法。", insight: "和昨天的自己比較就好，完成 10 分鐘也值得肯定。", color: "violet" },
	{ code: "WENCHANG05", name: "明德文昌宮", district: "臺南・府學街", badge: "明", story: "府城書院文化在這裡延續，學子會把願望寫在木牌上，約定日後回來回望一路的累積。", insight: "回看一個舊願望，寫下你已經做到的一小步。", color: "rose" },
];
type BarcodeDetectorInstance = { detect: (source: HTMLVideoElement) => Promise<{ rawValue: string }[]> };
type BarcodeDetectorConstructor = new (options?: { formats?: string[] }) => BarcodeDetectorInstance;
type ScannerWindow = Window & typeof globalThis & { BarcodeDetector?: BarcodeDetectorConstructor };
function qrCodeFromValue(value: string) { try { return new URL(value).searchParams.get("code")?.toUpperCase() ?? value.trim().toUpperCase(); } catch { return value.trim().toUpperCase(); } }

export default function Pilgrimage() {
	const [code, setCode] = useState(""); const [visits, setVisits] = useState<string[]>([]); const [notice, setNotice] = useState(""); const [idToken, setIdToken] = useState<string | null>(null); const [selectedTempleCode, setSelectedTempleCode] = useState<string | null>(null); const [scannerOpen, setScannerOpen] = useState(false);
	const videoRef = useRef<HTMLVideoElement>(null); const streamRef = useRef<MediaStream | null>(null); const animationRef = useRef<number | null>(null);
	const unlockedTemples = temples.filter((temple) => visits.includes(temple.code));
	const selectedTemple = temples.find((temple) => temple.code === selectedTempleCode) ?? unlockedTemples[0] ?? temples[0];
	useEffect(() => { try { setVisits(JSON.parse(localStorage.getItem("wenchang-mvp") ?? "{}").templeVisits ?? []); } catch {} liff.init({ liffId: LIFF_ID }).then(() => { if (liff.isLoggedIn()) setIdToken(liff.getIDToken()); }).catch(() => setNotice("LINE 巡禮同步暫時無法使用")); }, []);
	useEffect(() => { if (!idToken) return; fetch("/api/visits", { headers: { "x-line-id-token": idToken } }).then((response) => response.ok ? response.json() : Promise.reject()).then((data) => { if (Array.isArray(data.visits)) setVisits(data.visits); }).catch(() => setNotice("巡禮資料暫時只保存在此裝置")); }, [idToken]);
	useEffect(() => { if (!selectedTempleCode && unlockedTemples[0]) setSelectedTempleCode(unlockedTemples[0].code); }, [selectedTempleCode, unlockedTemples]);
	useEffect(() => { if (!scannerOpen) return; let cancelled = false; const stop = () => { if (animationRef.current) cancelAnimationFrame(animationRef.current); streamRef.current?.getTracks().forEach((track) => track.stop()); streamRef.current = null; }; const start = async () => { try { const Detector = (window as ScannerWindow).BarcodeDetector; if (!Detector) { setNotice("此瀏覽器暫不支援相機辨識，請使用巡禮碼手動解鎖。 "); setScannerOpen(false); return; } const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: "environment" }, audio: false }); if (cancelled) { stream.getTracks().forEach((track) => track.stop()); return; } streamRef.current = stream; const video = videoRef.current; if (!video) return; video.srcObject = stream; await video.play(); const detector = new Detector({ formats: ["qr_code"] }); const scan = async () => { if (cancelled || !videoRef.current) return; try { const result = await detector.detect(videoRef.current); if (result[0]?.rawValue) { setCode(qrCodeFromValue(result[0].rawValue)); setNotice("已讀取巡禮碼，請按「解鎖」確認。 "); setScannerOpen(false); return; } } catch {} animationRef.current = requestAnimationFrame(scan); }; void scan(); } catch { setNotice("無法開啟相機，請確認相機權限或改用手動輸入。 "); setScannerOpen(false); } }; void start(); return () => { cancelled = true; stop(); }; }, [scannerOpen]);
	const unlock = async () => { const normalized = qrCodeFromValue(code); const temple = temples.find((item) => item.code === normalized); if (!temple) { setNotice("這不是合作宮廟的巡禮碼。可使用 WENCHANG01 至 WENCHANG05 進行展示。 "); return; } setSelectedTempleCode(temple.code); if (visits.includes(normalized)) { setNotice(`「${temple.name}」已解鎖，點選下方文化卡可再次閱讀故事。`); return; } const next = [...visits, normalized]; setVisits(next); const plan = JSON.parse(localStorage.getItem("wenchang-mvp") ?? "{}"); localStorage.setItem("wenchang-mvp", JSON.stringify({ ...plan, templeVisits: next })); if (idToken) { const response = await fetch("/api/visits", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ idToken, code: normalized }) }); setNotice(response.ok ? `解鎖「${temple.name}」！文化故事與限定徽章已同步。` : `解鎖「${temple.name}」！目前暫存於此裝置。`); } else setNotice(`解鎖「${temple.name}」！登入 LINE 後可同步文化徽章。`); setCode(""); };
	return <main className="feature-page"><div className="feature-shell pilgrimage-shell"><button className="back-link" onClick={() => location.href = "/"}>← 返回</button><section className="feature-hero temple-hero"><span className="feature-kicker">SMART TEMPLE PILGRIMAGE</span><h1>為努力祈願，<br /><em>也為文化走一段路。</em></h1><p>掃描合作宮廟 QR Code，解鎖文昌文化故事、學習啟發與限定巡禮徽章。</p><div className="temple-illustration"><span>⛩</span><i>✦</i><i>✦</i><i>✦</i></div></section><section className="ritual-progress"><span>你的文化巡禮</span><b>{unlockedTemples.length}<small> / {temples.length} 站</small></b><div><i style={{ width: `${unlockedTemples.length / temples.length * 100}%` }} /></div></section><section className="scan-card"><div className="card-title"><span>⌁</span><div><b>掃描宮廟巡禮碼</b><small>掃描現場 QR Code；無法開啟相機時，也可輸入巡禮碼。</small></div></div><div className="code-row"><input value={code} onChange={(event) => setCode(event.target.value)} placeholder="例如 WENCHANG01" /><button onClick={unlock}>解鎖</button></div><button className="camera-scan-button" onClick={() => setScannerOpen((current) => !current)}>{scannerOpen ? "關閉相機" : "⌁ 開啟相機掃描 QR Code"}</button>{scannerOpen && <div className="qr-scanner"><video ref={videoRef} muted playsInline /><span>將 QR Code 對準框線</span></div>}{notice && <p className="unlock-notice">{notice}</p>}</section><section className="temple-route" aria-label="巡禮地圖">{temples.map((temple, index) => { const unlocked = visits.includes(temple.code); return <button key={temple.code} className={`temple-stop ${unlocked ? `unlocked ${temple.color}` : "locked"} ${selectedTemple.code === temple.code ? "selected" : ""}`} onClick={() => unlocked && setSelectedTempleCode(temple.code)} disabled={!unlocked}><span>{unlocked ? temple.badge : "?"}</span><div><small>第 {index + 1} 站</small><b>{unlocked ? temple.name : "尚待解鎖"}</b></div></button>; })}</section><section className={`culture-card temple-story ${selectedTemple.color}`}><div className="culture-symbol">{selectedTemple.badge}</div><div><span>{visits.includes(selectedTemple.code) ? `${selectedTemple.district}・已解鎖文化故事` : "下一站的文化故事"}</span><h2>{selectedTemple.name}</h2><p>{visits.includes(selectedTemple.code) ? selectedTemple.story : "前往合作宮廟掃描巡禮碼，解鎖這段文昌文化記憶。"}</p><div className="study-insight"><b>今日學習啟發</b><small>{visits.includes(selectedTemple.code) ? selectedTemple.insight : "每一站都會送你一句可以帶回今天的小練習。"}</small></div></div></section><section className="badge-card"><div><b>已收藏文化徽章</b><small>{unlockedTemples.length ? unlockedTemples.map((temple) => `${temple.badge}・${temple.name}`).join("　") : "尚未解鎖，第一枚文昌文化徽章正在等你"}</small></div><span>🌸</span></section><p className="feature-note">展示用巡禮碼：WENCHANG01 ～ WENCHANG05。正式合作時，將每座宮廟的專屬 QR Code 導向帶有 code 參數的巡禮連結即可。</p></div></main>;
}
